import { test, expect } from '@playwright/test';
const open=(page,user,path)=>page.goto(`/tests/marketing-ui/index.html?user=${user}&path=${encodeURIComponent(path)}`);
test('inherited campaign policy blocks a violating revision before Guardian without re-entering rules',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page,2,'/marketing/campaigns/new');await page.getByLabel('Name',{exact:true}).fill('Policy browser campaign');await page.getByRole('button',{name:'Save campaign',exact:true}).click();await page.getByLabel('Audience (comma separated)',{exact:true}).fill('Dealers');await page.getByRole('textbox',{name:'Channels (comma separated)',exact:true}).fill('social');await page.getByLabel('Primary CTA',{exact:true}).fill('Book a demo');await page.getByRole('button',{name:'Save brief',exact:true}).click();
  await page.getByText('Campaign settings & campaign approval',{exact:true}).click();const policy=page.getByRole('heading',{name:'Campaign Marketing Policy',exact:true}).locator('..');await policy.getByRole('checkbox',{name:'No unverified comparative claims',exact:true}).check();await policy.getByRole('button',{name:'Save Marketing Policy',exact:true}).click();await expect(policy.getByText(/Current version:/)).not.toContainText('No policy');
  await page.getByText('Add task',{exact:true}).click();await page.getByLabel('Task title',{exact:true}).fill('Policy governed copy');await page.getByRole('button',{name:'Create task',exact:true}).click();const summary=page.locator('summary').filter({hasText:'Policy governed copy · todo'});await summary.click();const task=summary.locator('..');await task.getByText('Guided Work',{exact:true}).click();await task.getByLabel('Execution workflow').selectOption('creator_guardian');await task.getByRole('button',{name:'Assign to Agent Team',exact:true}).click();const card=task.locator('.marketing-guided-work');await expect(card.getByRole('button',{name:'Approve',exact:true})).toBeVisible();await expect(card.getByText(/Campaign policy: 1 rules/).first()).toBeVisible();
  await card.getByRole('button',{name:'Request Changes',exact:true}).click();await card.getByLabel('What needs to change?').fill('Exercise constraint failure');await card.getByText('Add or update rules for this work',{exact:true}).click();await card.getByRole('button',{name:'Add prohibited phrase',exact:true}).click();await card.getByLabel('Prohibited phrase 1',{exact:true}).fill('competitive wholesale firearms');await card.getByRole('button',{name:'Request Changes & Send for Revision',exact:true}).click();
  await expect(card.getByText('Revision blocked by your Marketing Policy',{exact:true})).toBeVisible();await expect(card.getByRole('button',{name:'Approve',exact:true})).toHaveCount(0);await expect(card.getByText(/Detected:/).first()).toBeVisible();await card.getByRole('button',{name:'Send Back for Revision',exact:true}).click();await expect(card.getByRole('button',{name:'Approve',exact:true})).toBeVisible();await expect(card.getByText(/This review: 1 rules/).first()).toBeVisible();
  await card.getByRole('button',{name:'Approve',exact:true}).click();await card.getByRole('button',{name:'Mark Task Complete',exact:true}).click();await expect(page.locator('summary').filter({hasText:'Policy governed copy · done'})).toBeVisible();expect(errors).toEqual([]);
});
