import { test, expect } from '@playwright/test';

test('human review constraints stop a violating revision before Guardian and permit a clean human-authorized revision', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/tests/marketing-ui/index.html?user=1&path=/marketing/campaigns/new');
  await page.getByLabel('Name', { exact: true }).fill('Constraint browser campaign');
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await page.getByLabel('Audience (comma separated)', { exact: true }).fill('Dealers');
  await page.getByRole('textbox', { name: 'Channels (comma separated)', exact: true }).fill('social');
  await page.getByLabel('Primary CTA', { exact: true }).fill('Book a demo');
  await page.getByRole('button', { name: 'Save brief', exact: true }).click();
  await page.getByText('Add task', { exact: true }).click();
  await page.getByLabel('Task title', { exact: true }).fill('Constrained dealer copy');
  await page.getByRole('button', { name: 'Create task', exact: true }).click();
  const summary = page.locator('summary').filter({ hasText: 'Constrained dealer copy · todo' });
  const task = summary.locator('..');
  await summary.click(); await task.getByText('Agent execution', { exact: true }).click();
  await task.getByLabel('Execution workflow').selectOption('creator_guardian');
  await task.getByRole('button', { name: 'Assign to Agent Team', exact: true }).click();
  await expect(task.getByText('Ready for your review', { exact: true })).toBeVisible();
  const assetPath = await task.getByRole('link', { name: /Review manually/ }).getAttribute('href');
  const campaignPath = assetPath.split('?')[0];
  await task.getByRole('button', { name: 'Send to Approval', exact: true }).click();
  await page.goto(`/tests/marketing-ui/index.html?user=2&path=${encodeURIComponent(assetPath)}`);
  await page.getByRole('combobox', { name: 'Review decision', exact: true }).selectOption('request_changes');
  await page.getByLabel('Review notes / requested changes').fill('Remove unsupported comparative claims.');
  await page.getByRole('button', { name: 'Add prohibited phrase', exact: true }).click();
  await page.getByLabel('Prohibited phrase 1', { exact: true }).fill('competitive wholesale firearms');
  await page.getByRole('checkbox', { name: 'No unverified comparative claims', exact: true }).check();
  await page.getByRole('button', { name: 'Record human decision', exact: true }).click();
  await expect(page.locator('summary').filter({ hasText: 'Creator browser draft · social copy · changes requested' })).toBeVisible();
  await page.goto(`/tests/marketing-ui/index.html?user=1&path=${encodeURIComponent(campaignPath)}`);
  await summary.click(); await task.getByText('Agent execution', { exact: true }).click();
  await expect(task.getByText('prohibited phrase: competitive wholesale firearms', { exact: true })).toBeVisible();
  await task.getByLabel('Agent team instructions / revision notes').fill('Exercise constraint failure');
  await task.getByRole('button', { name: 'Send changes to Creator', exact: true }).click();
  await expect(task.getByRole('button', { name: 'Send constraint failures back to Creator', exact: true })).toBeVisible();
  await expect(task.getByText('Human constraint failed', { exact: true }).first()).toBeVisible();
  await expect(task.getByText(/Normalized text position/).first()).toBeVisible();
  await expect(page.locator('summary').filter({ hasText: 'guardian · succeeded' })).toHaveCount(1);
  await task.getByLabel('Agent team instructions / revision notes').fill('Use neutral factual wording.');
  await task.getByRole('button', { name: 'Send constraint failures back to Creator', exact: true }).click();
  await expect(task.getByText('Ready for your review', { exact: true })).toBeVisible();
  await expect(page.locator('summary').filter({ hasText: 'guardian · succeeded' })).toHaveCount(2);
  await task.getByRole('button', { name: 'Send to Approval', exact: true }).click();
  await page.goto(`/tests/marketing-ui/index.html?user=2&path=${encodeURIComponent(assetPath)}`);
  await page.getByRole('button', { name: 'Record human decision', exact: true }).click();
  await page.goto(`/tests/marketing-ui/index.html?user=1&path=${encodeURIComponent(campaignPath)}`);
  await summary.click(); await task.getByText('Agent execution', { exact: true }).click();
  await task.getByRole('button', { name: 'Mark task complete', exact: true }).click();
  await expect(page.locator('summary').filter({ hasText: 'Constrained dealer copy · done' })).toBeVisible();
  expect(errors).toEqual([]);
});
