import { test, expect } from '@playwright/test';

test('task assignment pauses at human plan and approval gates before explicit task completion', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/tests/marketing-ui/index.html?user=1&path=/marketing/campaigns/new');
  await page.getByLabel('Name', { exact: true }).fill('Orchestrated browser campaign');
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await page.getByLabel('Audience (comma separated)', { exact: true }).fill('Dealers');
  await page.getByRole('textbox', { name: 'Channels (comma separated)', exact: true }).fill('social');
  await page.getByLabel('Primary CTA', { exact: true }).fill('Book a demo');
  await page.getByRole('button', { name: 'Save brief', exact: true }).click();
  await page.getByText('Add task', { exact: true }).click();
  await page.getByLabel('Task title', { exact: true }).fill('Prepare task campaign copy');
  await page.getByRole('button', { name: 'Create task', exact: true }).click();
  const summary = page.locator('summary').filter({ hasText: 'Prepare task campaign copy · todo' });
  await summary.click();
  const task = summary.locator('..'); await task.getByText('Agent execution', { exact: true }).click();
  await expect(task.getByRole('button', { name: 'Assign to Agent Team', exact: true })).toBeDisabled();
  await task.getByLabel('Execution workflow').selectOption('strategist_creator_guardian');
  await task.getByRole('button', { name: 'Assign to Agent Team', exact: true }).click();
  await expect(task.getByRole('heading', { name: 'Plan decision needed' })).toBeVisible();
  await expect(task.getByRole('button', { name: 'Accept and continue' })).toBeVisible();
  await expect(task.getByText('Human action required', { exact: false })).toBeVisible();
  await task.getByRole('button', { name: 'Accept and continue' }).click();
  await expect(task.getByText('Ready for your review', { exact: true })).toBeVisible();
  await expect(summary).toContainText('todo');
  const assetPath = await task.getByRole('link', { name: /Review asset manually/ }).getAttribute('href');
  const campaignPath = assetPath.split('?')[0];
  await task.getByRole('button', { name: 'Send to Approval', exact: true }).click();
  await expect(task.getByRole('heading', { name: 'Approval decision needed' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Record human decision' })).toHaveCount(0);
  await page.goto(`/tests/marketing-ui/index.html?user=2&path=${encodeURIComponent(assetPath)}`);
  await page.getByRole('button', { name: 'Record human decision', exact: true }).click();
  await expect(page.locator('summary').filter({ hasText: 'Creator browser draft · social copy · approved' })).toBeVisible();
  await page.goto(`/tests/marketing-ui/index.html?user=1&path=${encodeURIComponent(campaignPath)}`);
  await summary.click(); await task.getByText('Agent execution', { exact: true }).click();
  await expect(task.getByRole('heading', { name: 'Completed' })).toBeVisible();
  await expect(task.getByText('Review recommended', { exact: false })).toBeVisible();
  await task.getByRole('button', { name: 'Mark Task Complete', exact: true }).click();
  await expect(page.locator('summary').filter({ hasText: 'Prepare task campaign copy · done' })).toBeVisible();
  await page.goto(`/tests/marketing-ui/index.html?user=3&path=${encodeURIComponent(campaignPath)}`);
  await page.locator('summary').filter({ hasText: 'Prepare task campaign copy · done' }).click();
  await page.getByText('Agent execution', { exact: true }).click();
  await expect(page.getByRole('button', { name: 'Assign to Agent Team', exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Completed' })).toBeVisible();
  expect(errors).toEqual([]);
});
