import { test, expect } from '@playwright/test';
const read=async page=>(await(await page.request.post('/__marketing_rpc',{headers:{'x-test-user':'2'},data:{name:'read_marketing_attention_workspace',args:{p_workspace:null}}})).json()).data;
const open=(page,user,path)=>page.goto(`/tests/marketing-ui/index.html?user=${user}&path=${encodeURIComponent(path)}`);
test('one guided feedback action recovers failed Guardian and approves in the same card',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page,2,'/marketing/campaigns/new');await page.getByLabel('Name',{exact:true}).fill('Recovery browser campaign');await page.getByRole('button',{name:'Save campaign',exact:true}).click();await page.getByLabel('Audience (comma separated)',{exact:true}).fill('Dealers');await page.getByRole('textbox',{name:'Channels (comma separated)',exact:true}).fill('social');await page.getByLabel('Primary CTA',{exact:true}).fill('Book a demo');await page.getByRole('button',{name:'Save brief',exact:true}).click();await page.getByText('Add task',{exact:true}).click();await page.getByLabel('Task title',{exact:true}).fill('Guided recovery');await page.getByRole('button',{name:'Create task',exact:true}).click();
  const summary=page.locator('summary').filter({hasText:'Guided recovery · todo'});await summary.click();const task=summary.locator('..');await task.getByText('Guided Work',{exact:true}).click();await task.getByLabel('Execution workflow').selectOption('creator_guardian');await task.getByLabel('Agent team instructions / revision notes').fill('Reproduce Guardian result rejection');await task.getByRole('button',{name:'Assign to Agent Team',exact:true}).click();
  const card=task.locator('.marketing-guided-work');await expect(card.getByRole('button',{name:'Continue this work',exact:true})).toBeVisible();let data=await read(page);const original=data.orchestrations.find(o=>o.task_id===data.tasks.find(t=>t.title==='Guided recovery').id);expect(original.state).toBe('failed');
  const sent=[];page.on('request',r=>{if(r.url().endsWith('/api/marketing-orchestration'))sent.push(r.postDataJSON());});await card.getByRole('button',{name:'Continue this work',exact:true}).click();await card.getByLabel('What needs to change?').fill('Use factual referral language.');await card.getByRole('button',{name:'Request Changes & Send for Revision',exact:true}).click();await expect(card.getByRole('button',{name:'Approve',exact:true})).toBeVisible();
  data=await read(page);const recovered=data.orchestrations.find(o=>o.id===original.id);expect(recovered.revision_cycles).toBe(1);expect(recovered.run_ids).toHaveLength(original.run_ids.length+2);
  const duplicate=await page.request.post('/api/marketing-orchestration',{headers:{Authorization:'Bearer 2'},data:sent.find(r=>r.action==='review')});expect(duplicate.ok()).toBe(true);expect((await duplicate.json()).orchestration.run_ids).toEqual(recovered.run_ids);
  await open(page,2,'/marketing/agents');const needs=page.getByRole('region',{name:/^Needs You/});const active=needs.locator('.marketing-guided-work').filter({hasText:'Guided recovery'});await expect(active).toHaveCount(1);const count=await needs.getByRole('article').count();await expect(page.getByRole('link',{name:'Agents',exact:true})).toHaveAccessibleDescription(`${count} unresolved items: Human action required`);
  await active.getByRole('button',{name:'Approve',exact:true}).click();await active.getByRole('button',{name:'Mark Task Complete',exact:true}).click();await expect(needs.locator('.marketing-guided-work').filter({hasText:'Guided recovery'})).toHaveCount(0);
  data=await read(page);expect(data.orchestration_history.some(h=>h.orchestration_id===original.id&&h.snapshot.state==='failed')).toBe(true);expect(data.attention_runs.find(r=>r.id===original.active_run_id).status).toBe('failed');expect(errors).toEqual([]);
});
