import { test, expect } from '@playwright/test';

const read = async page => (await (await page.request.post('/__marketing_rpc', { headers: { 'x-test-user': '1' }, data: { name: 'read_marketing_attention_workspace', args: { p_workspace: null } } })).json()).data;
const open = (page, user, path) => page.goto(`/tests/marketing-ui/index.html?user=${user}&path=${encodeURIComponent(path)}`);

test('asset-requested revision recovers rejected Guardian inside the original task and clears through human approval', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await open(page, 1, '/marketing/campaigns/new');
  await page.getByLabel('Name', { exact: true }).fill('Recovery browser campaign');
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await page.getByLabel('Audience (comma separated)', { exact: true }).fill('Dealers');
  await page.getByRole('textbox', { name: 'Channels (comma separated)', exact: true }).fill('social');
  await page.getByLabel('Primary CTA', { exact: true }).fill('Book a demo');
  await page.getByRole('button', { name: 'Save brief', exact: true }).click();
  await page.getByText('Add task', { exact: true }).click();
  await page.getByLabel('Task title', { exact: true }).fill('Referral recovery workflow');
  await page.getByRole('button', { name: 'Create task', exact: true }).click();
  const taskSummary = page.locator('summary').filter({ hasText: 'Referral recovery workflow · todo' });
  await taskSummary.click(); const task = taskSummary.locator('..');
  await task.getByText('Agent execution', { exact: true }).click();
  await task.getByLabel('Execution workflow').selectOption('strategist_creator_guardian');
  await task.getByLabel('Agent team instructions / revision notes').fill('Reproduce Guardian result rejection');
  await task.getByRole('button', { name: 'Assign to Agent Team', exact: true }).click();
  await task.getByRole('button', { name: 'Accept and continue' }).click();
  await expect(task.getByRole('heading', { name: 'Agent run failed', exact: true })).toBeVisible();
  let data = await read(page); const campaign = data.campaigns.find(c => c.name === 'Recovery browser campaign');
  const original = data.orchestrations.find(o => o.campaign_id === campaign.id);
  expect(original.reason).toBe('result_rejected');
  await open(page, 2, `/marketing/campaigns/${campaign.id}?asset=${original.asset_id}`);
  await page.getByRole('button', { name: 'Submit for review', exact: true }).click();
  await page.getByRole('combobox', { name: 'Review decision', exact: true }).selectOption('request_changes');
  await page.getByLabel('Review notes / requested changes').fill('Use factual referral language and keep the demo CTA.');
  await page.getByRole('button', { name: 'Add prohibited phrase', exact: true }).click();
  await page.getByLabel('Prohibited phrase 1', { exact: true }).fill('competitive wholesale firearms');
  await page.getByRole('button', { name: 'Record human decision', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Revise with Agent Team', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Send requested changes to Creator', exact: true })).toHaveCount(0);
  await expect(page.getByText(/This revision will continue the existing task workflow/)).toBeVisible();
  data = await read(page); const beforeAsset = data.assets.find(a => a.id === original.asset_id);
  const sent = []; page.on('request', request => { if (request.url().endsWith('/api/marketing-orchestration')) sent.push(request.postDataJSON()); });
  await page.getByRole('button', { name: 'Revise with Agent Team', exact: true }).click();
  await expect(page.locator('summary').filter({ hasText: 'Creator browser draft · social copy · draft' })).toBeVisible();
  data = await read(page); const recovered = data.orchestrations.find(o => o.id === original.id);
  expect(recovered.state).toBe('awaiting_review'); expect(recovered.revision_cycles).toBe(1); expect(recovered.asset_revision).toBe(beforeAsset.revision + 1);
  expect(recovered.run_ids).toHaveLength(original.run_ids.length + 2); expect(data.orchestrations.filter(o => o.task_id === original.task_id)).toHaveLength(1);
  const duplicate = await page.request.post('/api/marketing-orchestration', { headers: { Authorization: 'Bearer 2' }, data: sent.find(r => r.action === 'revise') });
  expect(duplicate.ok()).toBe(true); expect((await duplicate.json()).orchestration.run_ids).toEqual(recovered.run_ids);
  await page.getByRole('link', { name: 'Agents', exact: true }).click();
  const needs = page.getByRole('region', { name: /^Needs You/ });
  const card = needs.getByRole('article').filter({ hasText: 'Recovery browser campaign' });
  await expect(card).toHaveCount(1); await expect(card.getByRole('heading', { name: 'Ready for your review', exact: true })).toBeVisible();
  await expect(card.getByRole('list', { name: 'Workflow pipeline' }).locator('li').filter({ hasText: 'Guardian' })).toContainText('Completed');
  const count = await needs.getByRole('article').count();
  await expect(page.getByRole('link', { name: 'Agents', exact: true })).toHaveAccessibleDescription(`${count} unresolved items: Human action required`);
  await card.getByRole('button', { name: 'Review Asset', exact: true }).click();
  await expect(card.getByText('Latest human requested changes: Use factual referral language and keep the demo CTA.', { exact: true })).toBeVisible();
  await card.getByRole('button', { name: 'Send to Approval', exact: true }).click();
  const approvalLink = await card.getByRole('link', { name: 'Approve / Request Changes' }).getAttribute('href');
  expect(approvalLink).toContain(`asset=${original.asset_id}&revision=${recovered.asset_revision + 1}`);
  await open(page, 2, approvalLink);
  await page.getByRole('button', { name: 'Record human decision', exact: true }).click();
  await open(page, 1, '/marketing/agents');
  const completeCard = needs.getByRole('article').filter({ hasText: 'Recovery browser campaign' });
  await expect(completeCard.getByRole('heading', { name: 'Completed', exact: true })).toBeVisible();
  await completeCard.getByRole('button', { name: 'Mark Task Complete', exact: true }).click();
  await expect(needs.getByRole('article').filter({ hasText: 'Recovery browser campaign' })).toHaveCount(0);
  await expect(page.getByRole('region', { name: 'Recently Completed' }).getByRole('article').filter({ hasText: 'Recovery browser campaign' })).toHaveCount(1);
  data = await read(page);
  expect(data.orchestration_history.some(h => h.orchestration_id === original.id && h.snapshot.state === 'failed')).toBe(true);
  expect(data.attention_runs.find(r => r.id === original.active_run_id).status).toBe('failed');
  expect(errors).toEqual([]);
});
