import {test,expect} from '@playwright/test';
test('workspace policy is human managed, versioned, and imported only after explicit save',async({page})=>{
 const open=user=>page.goto(`/tests/marketing-ui/index.html?user=${user}&path=/marketing/settings`);
 await open(1);await expect(page.getByRole('heading',{name:'Workspace Marketing Policy',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save Marketing Policy',exact:true})).toHaveCount(0);
 await open(2);await page.getByText('Import policy draft',{exact:true}).click();await page.getByLabel('Policy rules JSON').fill(JSON.stringify([{constraint_type:'human_instruction',value:'Use verified business facts.'}]));await page.getByRole('button',{name:'Load draft for review',exact:true}).click();await expect(page.getByText('Current version: No policy configured',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save Marketing Policy',exact:true}).click();await expect(page.getByText(/Current version:/)).not.toContainText('No policy');
 await page.getByText('Policy version history',{exact:true}).click();await expect(page.getByText(/Human 00000000-0000-4000-8000-000000000002/)).toBeVisible();
 await page.getByText('Import policy draft',{exact:true}).click();await page.getByLabel('Policy rules JSON').fill('[]');await page.getByRole('button',{name:'Load draft for review',exact:true}).click();await page.getByRole('button',{name:'Save Marketing Policy',exact:true}).click();await expect(page.getByRole('button',{name:'Save Marketing Policy',exact:true})).toBeEnabled();const history=page.getByText('Policy version history',{exact:true}).locator('..');if(await history.getAttribute('open')===null)await page.getByText('Policy version history',{exact:true}).click();await expect(page.getByText(/Superseded · Version/)).toBeVisible();await expect(page.getByText('human instruction: Use verified business facts.',{exact:true})).toBeVisible();
 await open(3);await expect(page.getByRole('button',{name:'Save Marketing Policy',exact:true})).toHaveCount(0);
});
