import { test, expect } from '@playwright/test';

test('campaign brief through human approval with real local SQL RPCs', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const go = (user, path) => page.goto(`/tests/marketing-ui/index.html?user=${user}&path=${encodeURIComponent(path)}`);
  await go(1, '/marketing/campaigns/new');
  await page.getByLabel('Name', { exact: true }).fill('Workflow browser campaign');
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Campaign brief', exact: true })).toBeVisible();
  await page.getByLabel('Offer / value proposition').fill('Guided demo');
  await page.getByRole('button', { name: 'Add metric', exact: true }).click();
  await page.getByLabel('Metric', { exact: true }).fill('Bookings');
  await page.getByLabel('Target', { exact: true }).fill('20');
  await page.getByRole('button', { name: 'Save brief', exact: true }).click();
  await expect(page.getByLabel('Offer / value proposition')).toHaveValue('Guided demo');
  await page.getByText('Add task', { exact: true }).click();
  await page.getByLabel('Task title', { exact: true }).fill('Prepare copy');
  await page.getByLabel('Due date', { exact: true }).fill('2026-10-01');
  await page.getByRole('button', { name: 'Create task', exact: true }).click();
  await expect(page.locator('summary').filter({ hasText: 'Prepare copy · todo' })).toBeVisible();
  await page.getByText('Add draft asset', { exact: true }).click();
  await page.getByLabel('Asset name', { exact: true }).fill('Demo social copy');
  await page.getByRole('textbox', { name: 'Draft content', exact: true }).fill('Book your demo.');
  await page.getByRole('button', { name: 'Create draft asset', exact: true }).click();
  const summary = () => page.locator('summary').filter({ hasText: 'Demo social copy · social copy' });
  await summary().click();
  await page.getByRole('button', { name: 'Submit for review', exact: true }).click();
  await expect(summary()).toContainText('in review');
  await summary().click();
  await expect(page.getByRole('button', { name: 'Record human decision' })).toHaveCount(0);
  await page.getByRole('link', { name: 'Approvals', exact: true }).click();
  await expect(summary()).toBeVisible();
  await go(2, '/marketing/approvals');
  await summary().click();
  await page.getByText('Campaign context', { exact: true }).click();
  await expect(page.getByText('Guided demo', { exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Review decision', exact: true }).selectOption('request_changes');
  await page.getByLabel('Review notes / requested changes').fill('Mention a guided demo.');
  await page.getByRole('button', { name: 'Record human decision' }).click();
  await expect(summary()).toContainText('changes requested');
  await go(1, '/marketing/content');
  await summary().click();
  await page.getByText('Edit draft', { exact: true }).click();
  await summary().locator('..').getByRole('textbox', { name: 'Draft content', exact: true }).fill('Book your guided demo.');
  await summary().locator('..').getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(summary()).toContainText('draft');
  await summary().click();
  await page.getByRole('button', { name: 'Submit for review', exact: true }).click();
  await expect(summary()).toContainText('in review');
  await go(2, '/marketing/approvals');
  await summary().click();
  await page.getByLabel('Review notes / requested changes').fill('Ready; CTA verified.');
  await page.getByRole('button', { name: 'Record human decision' }).click();
  await expect(page.getByText('No assets awaiting review.', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Content', exact: true }).click();
  await expect(summary()).toContainText('approved');
  await summary().click();
  await summary().locator('..').getByText('Review & revision history', { exact: true }).click();
  await expect(page.getByText('Ready; CTA verified.', { exact: true })).toBeVisible();
  await expect(page.getByText('Mention a guided demo.', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/marketing-ui/approved-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/marketing-ui/approved-mobile.png', fullPage: true });
  await expect(page.locator('.vite-error-overlay')).toHaveCount(0);
  await go(3, '/marketing/content');
  await summary().click();
  await expect(page.getByText('Edit draft (resets approval)', { exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
