import { test, expect } from '@playwright/test';
const id = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const visit = (page, path = `/talent/candidates?workspace_id=${id(10)}`, user = '1') => page.goto(`/tests/talent-ui/index.html?${new URLSearchParams({ path, user })}`);
test('candidate list and 360 sections use the real authorized API with preserved history', async ({ page }) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await visit(page);
  await expect(page.getByRole('heading', { name: 'Talent Command Center' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Talent / People' })).toBeVisible();
  await expect(page.getByRole('row')).toHaveCount(5);
  const alex = page.getByRole('row').filter({ hasText: 'Alex Morgan' });
  await expect(alex).toContainText('candidate');
  await expect(alex).toContainText('in review');
  await expect(alex).toContainText('Production Assistant');
  await expect(alex).toContainText('Sam Rivera');
  await alex.locator('summary').click();
  await expect(alex).toContainText('last 7 days');
  await expect(alex).toContainText('2026-09-10T10:00:00Z');
  await page.screenshot({ path: 'test-results/talent-list.png', fullPage: true });
  await page.getByRole('link', { name: 'Alex Morgan', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Candidate 360' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Overview' })).toContainText('opted out');
  await page.getByRole('button', { name: 'Applications (3)', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Applications' })).toContainText('Sales Executive');
  await expect(page.getByRole('region', { name: 'Applications' })).toContainText('rejected');
  await expect(page.getByRole('region', { name: 'Applications' })).toContainText('Production Assistant');
  await page.locator('.talent-record').filter({ hasText: 'Sales Executive' }).getByText('Source details', { exact: true }).click();
  await expect(page.getByText('application-300', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Activity', exact: true }).click();
  await expect(page.locator('.talent-timeline li')).toHaveCount(5);
  await expect(page.locator('.talent-timeline li').first()).toContainText('Follow up with Alex');
  await expect(page.locator('.talent-timeline')).toContainText('Interview scheduled');
  await page.getByRole('button', { name: 'Documents', exact: true }).click();
  await expect(page.getByText('Alex resume.pdf', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Documents' }).getByRole('link')).toHaveCount(0);
  await page.getByRole('button', { name: 'Talent Journey', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No verified learner or employment linkage' })).toBeVisible();
  await expect(page.getByText('Learner linkage: Not verified', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/talent-journey.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('search, filters, pagination, workspace selection and empty state', async ({ page }) => {
  await visit(page, `/talent/candidates?workspace_id=${id(10)}&page_size=2`);
  await expect(page.getByRole('row')).toHaveCount(3);
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Alex Morgan', exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search candidates' }).fill('Sales Executive');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.getByRole('row')).toHaveCount(2);
  await expect(page.getByText('Page 1 of 1', { exact: true })).toBeVisible();
  await page.getByLabel('Lifecycle stage', { exact: true }).selectOption('learner');
  await expect(page.getByRole('heading', { name: 'No candidates match this view.' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
  await page.getByLabel('Latest application status', { exact: true }).selectOption('submitted');
  await expect(page.getByRole('row')).toHaveCount(3);
  await page.getByLabel('Owner', { exact: true }).selectOption('unassigned');
  await page.getByLabel('Source system', { exact: true }).selectOption('join-orion');
  await expect(page.getByRole('link', { name: 'Taylor Chen', exact: true })).toBeVisible();
  await page.getByLabel('Workspace', { exact: true }).selectOption(id(30));
  await expect(page.getByRole('heading', { name: 'No candidate records have been imported into the unified CRM yet.' })).toBeVisible();
  await expect(page.getByText(/Join-Orion migration\/integration is a separate step/)).toBeVisible();
});
test('foreign workspace and unauthorized sessions show errors with no retained candidate data', async ({ page }) => {
  await visit(page, `/talent/candidates?workspace_id=${id(20)}`);
  await expect(page.getByRole('alert')).toContainText('CRM workspace membership required');
  await expect(page.getByText('Private Candidate', { exact: true })).toHaveCount(0);
  await visit(page, `/talent/candidates?workspace_id=${id(10)}`, 'invalid');
  await expect(page.getByRole('alert')).toContainText('Verified human session required');
});
test('candidate without applications and mobile section navigation are safe', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await visit(page, `/talent/candidates/${id(101)}?workspace_id=${id(10)}`);
  await expect(page.getByRole('heading', { name: 'Jordan Lee', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Applications (0)', exact: true }).click();
  await expect(page.getByText('No applications are recorded for this candidate.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Talent Journey', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No verified learner or employment linkage' })).toBeVisible();
  await page.screenshot({ path: 'test-results/talent-mobile.png', fullPage: true });
});
